version: '3.4'

services:
  postgres:
    image: postgres:12.2
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cloud_analysis_manager
  grafana:
    image: grafana/grafana:6.5.0
    ports:
      - 3000:3000
  django:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres_data: