---
- name: Create VM Instance
  hosts: provisioner
  gather_facts: false
  roles:
    - role: gcs-bucket-upload
      tags: [ never, gcp ]

    - role: gce-create
      tags: [ never, gcp ]

    - role: aws-create
      tags: [ never, aws ]
