---
- name: Gather info on ansible's GCP service account
  gcp_iam_service_account_info:
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: serviceaccount

- name: Create a disk for GCE instance
  gcp_compute_disk:
    name: "{{ instance_name }}-{{ run_id }}-disk"
    size_gb: "{{ boot_disk_size }}"
    source_image: "{{ os_image }}"
    type: "{{ boot_disk_type }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: disk

- name: Create an IP address for GCE instance
  gcp_compute_address:
    name: "{{ instance_name }}-{{ run_id }}-ip"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: address

- name: Create a GCE instance
  gcp_compute_instance:
    name: "{{ instance_name }}-{{ run_id }}"
    machine_type: "{{ machine_type }}"
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
    metadata:
      google-logging-enabled: true
      gce-container-declaration: "spec:\n  containers:\n    - name: {{ instance_name }}\n      image: '{{ container_image }}'\n      env:\n        - name: RUN_ID\n          value: '{{ run_id }}'\n      stdin: false\n      tty: false\n  restartPolicy: Always\n"
    network_interfaces:
      - access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
    tags:
      items:
        - http-server
        - https-server
    service_accounts:
      - email: "{{ serviceaccount.resources[0].email if serviceaccount }}"
        scopes:
          - https://www.googleapis.com/auth/cloud-platform
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: instance

- name: Print GCE instance ip
  debug:
    msg: "IP address for instance {{ instance.name }}: {{ address.address }}"
