# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConstNodeData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ConstNodeData.proto',
  package='TruNavNodePack1.Nodes.Input.NodeData',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x43onstNodeData.proto\x12$TruNavNodePack1.Nodes.Input.NodeData\"$\n\nCustomGuid\x12\n\n\x02lo\x18\x01 \x02(\x06\x12\n\n\x02hi\x18\x02 \x02(\x06\"\xd8\x01\n\rConstNodeData\x12N\n\x0c\x41llLayerData\x18\x01 \x03(\x0b\x32\x38.TruNavNodePack1.Nodes.Input.NodeData.ConstNodeLayerData\x12L\n\nCachedData\x18\x02 \x03(\x0b\x32\x38.TruNavNodePack1.Nodes.Input.NodeData.ConstNodeLayerData\x12)\n\x1aNodeDataSharedAcrossLayers\x18\x03 \x01(\x08:\x05\x66\x61lse\"\xd8\x01\n\x12\x43onstNodeLayerData\x12\x41\n\x07LayerId\x18\x01 \x01(\x0b\x32\x30.TruNavNodePack1.Nodes.Input.NodeData.CustomGuid\x12\x11\n\tLayerName\x18\x02 \x01(\t\x12\x14\n\tConstData\x18\x03 \x01(\x01:\x01\x30\x12\x11\n\tDataNotes\x18\x04 \x01(\t\x12\x43\n\tDataSetId\x18\x05 \x01(\x0b\x32\x30.TruNavNodePack1.Nodes.Input.NodeData.CustomGuid')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CUSTOMGUID = _descriptor.Descriptor(
  name='CustomGuid',
  full_name='TruNavNodePack1.Nodes.Input.NodeData.CustomGuid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lo', full_name='TruNavNodePack1.Nodes.Input.NodeData.CustomGuid.lo', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hi', full_name='TruNavNodePack1.Nodes.Input.NodeData.CustomGuid.hi', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=97,
)


_CONSTNODEDATA = _descriptor.Descriptor(
  name='ConstNodeData',
  full_name='TruNavNodePack1.Nodes.Input.NodeData.ConstNodeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AllLayerData', full_name='TruNavNodePack1.Nodes.Input.NodeData.ConstNodeData.AllLayerData', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CachedData', full_name='TruNavNodePack1.Nodes.Input.NodeData.ConstNodeData.CachedData', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NodeDataSharedAcrossLayers', full_name='TruNavNodePack1.Nodes.Input.NodeData.ConstNodeData.NodeDataSharedAcrossLayers', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=316,
)


_CONSTNODELAYERDATA = _descriptor.Descriptor(
  name='ConstNodeLayerData',
  full_name='TruNavNodePack1.Nodes.Input.NodeData.ConstNodeLayerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LayerId', full_name='TruNavNodePack1.Nodes.Input.NodeData.ConstNodeLayerData.LayerId', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LayerName', full_name='TruNavNodePack1.Nodes.Input.NodeData.ConstNodeLayerData.LayerName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ConstData', full_name='TruNavNodePack1.Nodes.Input.NodeData.ConstNodeLayerData.ConstData', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DataNotes', full_name='TruNavNodePack1.Nodes.Input.NodeData.ConstNodeLayerData.DataNotes', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DataSetId', full_name='TruNavNodePack1.Nodes.Input.NodeData.ConstNodeLayerData.DataSetId', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=535,
)

_CONSTNODEDATA.fields_by_name['AllLayerData'].message_type = _CONSTNODELAYERDATA
_CONSTNODEDATA.fields_by_name['CachedData'].message_type = _CONSTNODELAYERDATA
_CONSTNODELAYERDATA.fields_by_name['LayerId'].message_type = _CUSTOMGUID
_CONSTNODELAYERDATA.fields_by_name['DataSetId'].message_type = _CUSTOMGUID
DESCRIPTOR.message_types_by_name['CustomGuid'] = _CUSTOMGUID
DESCRIPTOR.message_types_by_name['ConstNodeData'] = _CONSTNODEDATA
DESCRIPTOR.message_types_by_name['ConstNodeLayerData'] = _CONSTNODELAYERDATA

CustomGuid = _reflection.GeneratedProtocolMessageType('CustomGuid', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMGUID,
  __module__ = 'ConstNodeData_pb2'
  # @@protoc_insertion_point(class_scope:TruNavNodePack1.Nodes.Input.NodeData.CustomGuid)
  ))
_sym_db.RegisterMessage(CustomGuid)

ConstNodeData = _reflection.GeneratedProtocolMessageType('ConstNodeData', (_message.Message,), dict(
  DESCRIPTOR = _CONSTNODEDATA,
  __module__ = 'ConstNodeData_pb2'
  # @@protoc_insertion_point(class_scope:TruNavNodePack1.Nodes.Input.NodeData.ConstNodeData)
  ))
_sym_db.RegisterMessage(ConstNodeData)

ConstNodeLayerData = _reflection.GeneratedProtocolMessageType('ConstNodeLayerData', (_message.Message,), dict(
  DESCRIPTOR = _CONSTNODELAYERDATA,
  __module__ = 'ConstNodeData_pb2'
  # @@protoc_insertion_point(class_scope:TruNavNodePack1.Nodes.Input.NodeData.ConstNodeLayerData)
  ))
_sym_db.RegisterMessage(ConstNodeLayerData)


# @@protoc_insertion_point(module_scope)
