# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InputNodeData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='InputNodeData.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13InputNodeData.proto\"\xca\x02\n\rInputNodeData\x12&\n\tLayerData\x18\x01 \x03(\x0b\x32\x13.InputNodeLayerData\x12=\n\x14NodeDistributionType\x18\x02 \x01(\x0e\x32\x15.DistributionTypeEnum:\x08Gaussian\x12>\n\rRoundingStage\x18\x03 \x01(\x0e\x32\x1f.InputIteratorRoundingStageEnum:\x06\x42\x65\x66ore\x12>\n\x0cResultAction\x18\x04 \x01(\x0e\x32\x1f.InputIteratorResultActionsEnum:\x07\x41verage\x12\'\n\nCachedData\x18\x05 \x03(\x0b\x32\x13.InputNodeLayerData\x12)\n\x1aNodeDataSharedAcrossLayers\x18\x06 \x01(\x08:\x05\x66\x61lse\"\xb6\x01\n\x12InputNodeLayerData\x12\x1c\n\x07LayerId\x18\x01 \x01(\x0b\x32\x0b.CustomGuid\x12\x11\n\tLayerName\x18\x02 \x01(\t\x12$\n\tInputData\x18\x03 \x01(\x0b\x32\x11.UncertaintyRange\x12\x11\n\tDataNotes\x18\x04 \x01(\t\x12\x16\n\x0bRepeatCount\x18\x05 \x01(\x05:\x01\x30\x12\x1e\n\tDataSetId\x18\x06 \x01(\x0b\x32\x0b.CustomGuid\"u\n\x10UncertaintyRange\x12\x0e\n\x03Low\x18\x01 \x01(\x01:\x01\x30\x12\x12\n\x07Nominal\x18\x02 \x01(\x01:\x01\x30\x12\x0f\n\x04High\x18\x03 \x01(\x01:\x01\x30\x12\x15\n\nLowerBound\x18\x04 \x01(\x01:\x01\x30\x12\x15\n\nUpperBound\x18\x05 \x01(\x01:\x01\x30\"$\n\nCustomGuid\x12\n\n\x02lo\x18\x01 \x02(\x06\x12\n\n\x02hi\x18\x02 \x02(\x06*1\n\x14\x44istributionTypeEnum\x12\x0c\n\x08Gaussian\x10\x00\x12\x0b\n\x07Uniform\x10\x01*6\n\x1eInputIteratorResultActionsEnum\x12\x0b\n\x07\x41verage\x10\x00\x12\x07\n\x03Sum\x10\x01*A\n\x1eInputIteratorRoundingStageEnum\x12\n\n\x06\x42\x65\x66ore\x10\x00\x12\t\n\x05\x41\x66ter\x10\x01\x12\x08\n\x04\x42oth\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DISTRIBUTIONTYPEENUM = _descriptor.EnumDescriptor(
  name='DistributionTypeEnum',
  full_name='DistributionTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Gaussian', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Uniform', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=698,
  serialized_end=747,
)
_sym_db.RegisterEnumDescriptor(_DISTRIBUTIONTYPEENUM)

DistributionTypeEnum = enum_type_wrapper.EnumTypeWrapper(_DISTRIBUTIONTYPEENUM)
_INPUTITERATORRESULTACTIONSENUM = _descriptor.EnumDescriptor(
  name='InputIteratorResultActionsEnum',
  full_name='InputIteratorResultActionsEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Average', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sum', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=749,
  serialized_end=803,
)
_sym_db.RegisterEnumDescriptor(_INPUTITERATORRESULTACTIONSENUM)

InputIteratorResultActionsEnum = enum_type_wrapper.EnumTypeWrapper(_INPUTITERATORRESULTACTIONSENUM)
_INPUTITERATORROUNDINGSTAGEENUM = _descriptor.EnumDescriptor(
  name='InputIteratorRoundingStageEnum',
  full_name='InputIteratorRoundingStageEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Before', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='After', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Both', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=805,
  serialized_end=870,
)
_sym_db.RegisterEnumDescriptor(_INPUTITERATORROUNDINGSTAGEENUM)

InputIteratorRoundingStageEnum = enum_type_wrapper.EnumTypeWrapper(_INPUTITERATORROUNDINGSTAGEENUM)
Gaussian = 0
Uniform = 1
Average = 0
Sum = 1
Before = 0
After = 1
Both = 2



_INPUTNODEDATA = _descriptor.Descriptor(
  name='InputNodeData',
  full_name='InputNodeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LayerData', full_name='InputNodeData.LayerData', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NodeDistributionType', full_name='InputNodeData.NodeDistributionType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RoundingStage', full_name='InputNodeData.RoundingStage', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ResultAction', full_name='InputNodeData.ResultAction', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CachedData', full_name='InputNodeData.CachedData', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NodeDataSharedAcrossLayers', full_name='InputNodeData.NodeDataSharedAcrossLayers', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=354,
)


_INPUTNODELAYERDATA = _descriptor.Descriptor(
  name='InputNodeLayerData',
  full_name='InputNodeLayerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LayerId', full_name='InputNodeLayerData.LayerId', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LayerName', full_name='InputNodeLayerData.LayerName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='InputData', full_name='InputNodeLayerData.InputData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DataNotes', full_name='InputNodeLayerData.DataNotes', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RepeatCount', full_name='InputNodeLayerData.RepeatCount', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DataSetId', full_name='InputNodeLayerData.DataSetId', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=539,
)


_UNCERTAINTYRANGE = _descriptor.Descriptor(
  name='UncertaintyRange',
  full_name='UncertaintyRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Low', full_name='UncertaintyRange.Low', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Nominal', full_name='UncertaintyRange.Nominal', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='High', full_name='UncertaintyRange.High', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LowerBound', full_name='UncertaintyRange.LowerBound', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UpperBound', full_name='UncertaintyRange.UpperBound', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=658,
)


_CUSTOMGUID = _descriptor.Descriptor(
  name='CustomGuid',
  full_name='CustomGuid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lo', full_name='CustomGuid.lo', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hi', full_name='CustomGuid.hi', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=696,
)

_INPUTNODEDATA.fields_by_name['LayerData'].message_type = _INPUTNODELAYERDATA
_INPUTNODEDATA.fields_by_name['NodeDistributionType'].enum_type = _DISTRIBUTIONTYPEENUM
_INPUTNODEDATA.fields_by_name['RoundingStage'].enum_type = _INPUTITERATORROUNDINGSTAGEENUM
_INPUTNODEDATA.fields_by_name['ResultAction'].enum_type = _INPUTITERATORRESULTACTIONSENUM
_INPUTNODEDATA.fields_by_name['CachedData'].message_type = _INPUTNODELAYERDATA
_INPUTNODELAYERDATA.fields_by_name['LayerId'].message_type = _CUSTOMGUID
_INPUTNODELAYERDATA.fields_by_name['InputData'].message_type = _UNCERTAINTYRANGE
_INPUTNODELAYERDATA.fields_by_name['DataSetId'].message_type = _CUSTOMGUID
DESCRIPTOR.message_types_by_name['InputNodeData'] = _INPUTNODEDATA
DESCRIPTOR.message_types_by_name['InputNodeLayerData'] = _INPUTNODELAYERDATA
DESCRIPTOR.message_types_by_name['UncertaintyRange'] = _UNCERTAINTYRANGE
DESCRIPTOR.message_types_by_name['CustomGuid'] = _CUSTOMGUID
DESCRIPTOR.enum_types_by_name['DistributionTypeEnum'] = _DISTRIBUTIONTYPEENUM
DESCRIPTOR.enum_types_by_name['InputIteratorResultActionsEnum'] = _INPUTITERATORRESULTACTIONSENUM
DESCRIPTOR.enum_types_by_name['InputIteratorRoundingStageEnum'] = _INPUTITERATORROUNDINGSTAGEENUM

InputNodeData = _reflection.GeneratedProtocolMessageType('InputNodeData', (_message.Message,), dict(
  DESCRIPTOR = _INPUTNODEDATA,
  __module__ = 'InputNodeData_pb2'
  # @@protoc_insertion_point(class_scope:InputNodeData)
  ))
_sym_db.RegisterMessage(InputNodeData)

InputNodeLayerData = _reflection.GeneratedProtocolMessageType('InputNodeLayerData', (_message.Message,), dict(
  DESCRIPTOR = _INPUTNODELAYERDATA,
  __module__ = 'InputNodeData_pb2'
  # @@protoc_insertion_point(class_scope:InputNodeLayerData)
  ))
_sym_db.RegisterMessage(InputNodeLayerData)

UncertaintyRange = _reflection.GeneratedProtocolMessageType('UncertaintyRange', (_message.Message,), dict(
  DESCRIPTOR = _UNCERTAINTYRANGE,
  __module__ = 'InputNodeData_pb2'
  # @@protoc_insertion_point(class_scope:UncertaintyRange)
  ))
_sym_db.RegisterMessage(UncertaintyRange)

CustomGuid = _reflection.GeneratedProtocolMessageType('CustomGuid', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMGUID,
  __module__ = 'InputNodeData_pb2'
  # @@protoc_insertion_point(class_scope:CustomGuid)
  ))
_sym_db.RegisterMessage(CustomGuid)


# @@protoc_insertion_point(module_scope)
