# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NodeTagListBlob.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NodeTagListBlob.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15NodeTagListBlob.proto\"\x1c\n\x0bList_String\x12\r\n\x05items\x18\x01 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LIST_STRING = _descriptor.Descriptor(
  name='List_String',
  full_name='List_String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='List_String.items', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['List_String'] = _LIST_STRING

List_String = _reflection.GeneratedProtocolMessageType('List_String', (_message.Message,), dict(
  DESCRIPTOR = _LIST_STRING,
  __module__ = 'NodeTagListBlob_pb2'
  # @@protoc_insertion_point(class_scope:List_String)
  ))
_sym_db.RegisterMessage(List_String)


# @@protoc_insertion_point(module_scope)
