# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TagFilterOption.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TagFilterOption.proto',
  package='NodeSystem.Tags',
  syntax='proto2',
  serialized_pb=_b('\n\x15TagFilterOption.proto\x12\x0fNodeSystem.Tags\"G\n\x14List_TagFilterOption\x12/\n\x05items\x18\x01 \x03(\x0b\x32 .NodeSystem.Tags.TagFilterOption\"\xca\x01\n\x0fTagFilterOption\x12\'\n\x02Id\x18\x01 \x01(\x0b\x32\x1b.NodeSystem.Tags.CustomGuid\x12\x13\n\x0b\x44isplayName\x18\x02 \x01(\t\x12\x0b\n\x03Tag\x18\x03 \x01(\t\x12\x19\n\nIsSelected\x18\x04 \x01(\x08:\x05\x66\x61lse\x12Q\n\x10\x46ilterOptionType\x18\x05 \x01(\x0e\x32-.NodeSystem.Tags.CategoryFilterOptionTypeEnum:\x08TagMatch\"$\n\nCustomGuid\x12\n\n\x02lo\x18\x01 \x02(\x06\x12\n\n\x02hi\x18\x02 \x02(\x06*T\n\x1c\x43\x61tegoryFilterOptionTypeEnum\x12\x0c\n\x08TagMatch\x10\x00\x12\x14\n\x07Unknown\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x10\n\x0cNameContains\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CATEGORYFILTEROPTIONTYPEENUM = _descriptor.EnumDescriptor(
  name='CategoryFilterOptionTypeEnum',
  full_name='NodeSystem.Tags.CategoryFilterOptionTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TagMatch', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=1, number=-1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NameContains', index=2, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=358,
  serialized_end=442,
)
_sym_db.RegisterEnumDescriptor(_CATEGORYFILTEROPTIONTYPEENUM)

CategoryFilterOptionTypeEnum = enum_type_wrapper.EnumTypeWrapper(_CATEGORYFILTEROPTIONTYPEENUM)
TagMatch = 0
Unknown = -1
NameContains = 1



_LIST_TAGFILTEROPTION = _descriptor.Descriptor(
  name='List_TagFilterOption',
  full_name='NodeSystem.Tags.List_TagFilterOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='NodeSystem.Tags.List_TagFilterOption.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=113,
)


_TAGFILTEROPTION = _descriptor.Descriptor(
  name='TagFilterOption',
  full_name='NodeSystem.Tags.TagFilterOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='NodeSystem.Tags.TagFilterOption.Id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DisplayName', full_name='NodeSystem.Tags.TagFilterOption.DisplayName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Tag', full_name='NodeSystem.Tags.TagFilterOption.Tag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IsSelected', full_name='NodeSystem.Tags.TagFilterOption.IsSelected', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FilterOptionType', full_name='NodeSystem.Tags.TagFilterOption.FilterOptionType', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=318,
)


_CUSTOMGUID = _descriptor.Descriptor(
  name='CustomGuid',
  full_name='NodeSystem.Tags.CustomGuid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lo', full_name='NodeSystem.Tags.CustomGuid.lo', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hi', full_name='NodeSystem.Tags.CustomGuid.hi', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=356,
)

_LIST_TAGFILTEROPTION.fields_by_name['items'].message_type = _TAGFILTEROPTION
_TAGFILTEROPTION.fields_by_name['Id'].message_type = _CUSTOMGUID
_TAGFILTEROPTION.fields_by_name['FilterOptionType'].enum_type = _CATEGORYFILTEROPTIONTYPEENUM
DESCRIPTOR.message_types_by_name['List_TagFilterOption'] = _LIST_TAGFILTEROPTION
DESCRIPTOR.message_types_by_name['TagFilterOption'] = _TAGFILTEROPTION
DESCRIPTOR.message_types_by_name['CustomGuid'] = _CUSTOMGUID
DESCRIPTOR.enum_types_by_name['CategoryFilterOptionTypeEnum'] = _CATEGORYFILTEROPTIONTYPEENUM

List_TagFilterOption = _reflection.GeneratedProtocolMessageType('List_TagFilterOption', (_message.Message,), dict(
  DESCRIPTOR = _LIST_TAGFILTEROPTION,
  __module__ = 'TagFilterOption_pb2'
  # @@protoc_insertion_point(class_scope:NodeSystem.Tags.List_TagFilterOption)
  ))
_sym_db.RegisterMessage(List_TagFilterOption)

TagFilterOption = _reflection.GeneratedProtocolMessageType('TagFilterOption', (_message.Message,), dict(
  DESCRIPTOR = _TAGFILTEROPTION,
  __module__ = 'TagFilterOption_pb2'
  # @@protoc_insertion_point(class_scope:NodeSystem.Tags.TagFilterOption)
  ))
_sym_db.RegisterMessage(TagFilterOption)

CustomGuid = _reflection.GeneratedProtocolMessageType('CustomGuid', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMGUID,
  __module__ = 'TagFilterOption_pb2'
  # @@protoc_insertion_point(class_scope:NodeSystem.Tags.CustomGuid)
  ))
_sym_db.RegisterMessage(CustomGuid)


# @@protoc_insertion_point(module_scope)
