# Generated by Django 3.0 on 2020-02-11 17:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
                ('file_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AnalyticsSolution')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('exec_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ExecutiveView')),
            ],
        ),
        migrations.CreateModel(
            name='InputDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InputPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AnalyticsSolution')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InputDataSet')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AnalyticsSolution')),
            ],
        ),
        migrations.CreateModel(
            name='InputPageDsAsc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_value', models.DecimalField(decimal_places=5, max_digits=15)),
                ('mid_value', models.DecimalField(decimal_places=5, max_digits=15)),
                ('high_value', models.DecimalField(decimal_places=5, max_digits=15)),
                ('lower_bound', models.DecimalField(decimal_places=5, max_digits=15)),
                ('upper_bound', models.DecimalField(decimal_places=5, max_digits=15)),
                ('ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InputDataSet', verbose_name='Input Data Set')),
                ('inputPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InputPage', verbose_name='Input Data Set')),
                ('scenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario', verbose_name='Input Data Set')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inputpage',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Model'),
        ),
        migrations.AddField(
            model_name='inputdataset',
            name='input_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InputPage'),
        ),
        migrations.CreateModel(
            name='InputChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('ids', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.InputDataSet')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Input')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.inputchoice_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='EvalJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Result', django.contrib.postgres.fields.jsonb.JSONField()),
                ('DateCreated', models.DateTimeField()),
                ('Status', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AnalyticsSolution')),
            ],
        ),
    ]
