# Generated by Django 3.0 on 2020-03-24 20:12

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('tam_file', models.FileField(upload_to=app.models._name_tam_file)),
            ],
        ),
        migrations.CreateModel(
            name='EvalJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AnalyticsSolution')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exec_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ExecutiveView')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_adhoc', models.BooleanField(default=False)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AnalyticsSolution')),
            ],
        ),
        migrations.CreateModel(
            name='NodeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('node', models.CharField(max_length=255)),
                ('layer', models.CharField(max_length=255)),
                ('result_10', models.FloatField()),
                ('result_30', models.FloatField()),
                ('result_50', models.FloatField()),
                ('result_70', models.FloatField()),
                ('result_90', models.FloatField()),
                ('eval_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EvalJob')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AnalyticsSolution')),
            ],
        ),
        migrations.CreateModel(
            name='InputPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Model')),
            ],
        ),
        migrations.CreateModel(
            name='InputDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=app.models._name_ids_file)),
                ('input_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InputPage')),
                ('scenarios', models.ManyToManyField(to='app.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='InputChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InputDataSet', verbose_name='Data Set')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Input')),
            ],
        ),
        migrations.AddField(
            model_name='evaljob',
            name='adhoc_scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario'),
        ),
        migrations.AddField(
            model_name='evaljob',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AnalyticsSolution'),
        ),
    ]
