# Generated by Django 3.0 on 2020-09-17 17:30

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('defaults', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioNodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overrides', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('is_uncertain', models.BooleanField(default=False)),
                ('is_bounded', models.BooleanField(default=False)),
                ('is_changes', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='inputdataset',
            name='scenarios',
            field=models.ManyToManyField(blank=True, to='app.Scenario'),
        ),
        migrations.AlterField(
            model_name='noderesult',
            name='layer',
            field=models.DateField(),
        ),
    ]
