# Generated by Django 3.0 on 2020-02-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='name',
        ),
    ]
