# Generated by Django 3.0 on 2020-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_input_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='label',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
