# Generated by Django 3.0 on 2020-03-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_evaljob_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('node', models.CharField(max_length=255)),
                ('layer', models.CharField(max_length=255)),
                ('result_10', models.FloatField()),
                ('result_30', models.FloatField()),
                ('result_50', models.FloatField()),
                ('result_70', models.FloatField()),
                ('result_90', models.FloatField()),
                ('eval_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EvalJob')),
            ],
        ),
    ]
