# Generated by Django 3.0 on 2020-09-17 18:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200917_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecimalNodeOverride',
            fields=[
                ('nodeoverride_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.NodeOverride')),
                ('value', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.nodeoverride',),
        ),
        migrations.RenameField(
            model_name='nodedata',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scenarionodedata',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='analyticssolution',
            name='dashboard_uid',
            field=models.CharField(editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='analyticssolution',
            name='dashboard_url',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='evaljob',
            name='errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='nodedata',
            name='node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Node'),
        ),
        migrations.AddField(
            model_name='scenarionodedata',
            name='node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Node'),
        ),
        migrations.AddField(
            model_name='scenarionodedata',
            name='scenario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Scenario'),
        ),
        migrations.AlterField(
            model_name='evaljob',
            name='layer_time_start',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='IntegerNodeOverride',
        ),
    ]
