# Generated by Django 3.0 on 2020-02-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_input_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='label',
            new_name='name',
        ),
        migrations.AddField(
            model_name='executiveview',
            name='name',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
    ]
