# Generated by Django 3.0 on 2020-09-18 19:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0003_auto_20200917_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodedata',
            name='defaults',
        ),
        migrations.CreateModel(
            name='ConstNodeData',
            fields=[
                ('nodedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.NodeData')),
                ('defaults', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=15), size=None)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.nodedata',),
        ),
        migrations.CreateModel(
            name='InputNodeData',
            fields=[
                ('nodedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.NodeData')),
                ('defaults', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=15), size=None), size=None)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.nodedata',),
        ),
        migrations.AlterModelOptions(
            name='nodedata',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='nodedata',
            name='name',
        ),
        migrations.AddField(
            model_name='nodedata',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.nodedata_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='analyticssolution',
            name='dashboard_uid',
            field=models.CharField(default='', editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='analyticssolution',
            name='dashboard_url',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
