# Generated by Django 3.0 on 2020-09-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200918_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constnodedata',
            old_name='defaults',
            new_name='default_data',
        ),
        migrations.RenameField(
            model_name='inputnodedata',
            old_name='defaults',
            new_name='default_data',
        ),
    ]
