# Generated by Django 3.0 on 2020-03-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_scenariodataset_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tables',
        ),
    ]
