# Generated by Django 3.0 on 2020-09-22 21:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200918_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
