# Generated by Django 3.0 on 2020-02-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0005_auto_20200211_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputchoice',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='inputchoice',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.inputchoice_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='inputchoice',
            name='ids',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.InputDataSet'),
        ),
    ]
