# Generated by Django 3.0 on 2020-02-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200211_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='Choices',
            field=models.CharField(choices=[('High', 'High'), ('Average', 'Average'), ('Low', 'Low')], default='Low', max_length=20),
            preserve_default=False,
        ),
    ]
