# Generated by Django 3.0 on 2020-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_filtercategory_filteroption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filteroption',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='filteroption',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
