# Generated by Django 3.0 on 2020-02-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_input_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssolution',
            name='file_url',
            field=models.URLField(max_length=255),
        ),
    ]
