# Generated by Django 3.0 on 2020-02-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200211_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputchoice',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
