# Generated by Django 3.0 on 2020-10-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200928_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssolution',
            name='report_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='analyticssolution',
            name='workspace_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
