# Generated by Django 3.0 on 2020-02-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_inputchoice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputchoice',
            name='ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InputDataSet'),
        ),
    ]
