# Generated by Django 3.0 on 2020-10-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201012_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodedata',
            name='is_model',
            field=models.BooleanField(default=True),
        ),
    ]
