# Generated by Django 3.0 on 2020-02-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200217_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputpagedsasc',
            name='inputPage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InputPage', verbose_name='Input Page'),
        ),
        migrations.AlterField(
            model_name='inputpagedsasc',
            name='scenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario', verbose_name='Scenario'),
        ),
    ]
