# Generated by Django 3.0 on 2020-10-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_nodedata_is_model'),
    ]

    operations = [
    ]
