# Generated by Django 3.0 on 2020-02-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='Choices',
        ),
    ]
