# Generated by Django 3.0 on 2020-10-28 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201019_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 28)),
        ),
        migrations.AddField(
            model_name='scenario',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
