# Generated by Django 3.0 on 2020-10-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201022_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarionodedata',
            name='is_in_progress',
        ),
        migrations.AddField(
            model_name='scenario',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
