# Generated by Django 3.0 on 2020-10-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_nodedata_scenario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScenarioNodeData',
        ),
    ]
