# Generated by Django 3.0 on 2020-10-26 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_scenarionodedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedata',
            name='scenario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Scenario'),
        ),
    ]
