# Generated by Django 3.0 on 2020-10-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201028_1133'),
        ('app', '0018_auto_20201026_1725'),
    ]

    operations = [
    ]
