# Generated by Django 3.0 on 2020-11-20 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_merge_20201028_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderesult',
            name='role',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='shared',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
