# Generated by Django 3.0 on 2020-11-20 22:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20201028_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='solution',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.AnalyticsSolution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scenario',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 20)),
        ),
    ]
