# Generated by Django 3.0 on 2020-12-02 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('app', '0020_auto_20201120_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssolution',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Role'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 2)),
        ),
    ]
