# Generated by Django 3.0 on 2020-11-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201120_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='exec_view',
        ),
    ]
