# Generated by Django 3.0 on 2020-12-03 16:48

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201201_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='date',
        ),
        migrations.AlterField(
            model_name='nodedata',
            name='node',
            field=models.ForeignKey(default=None, on_delete=app.models.NON_POLYMORPHIC_CASCADE, to='app.Node'),
        ),
        migrations.AlterField(
            model_name='nodedata',
            name='scenario',
            field=models.ForeignKey(default=None, null=True, on_delete=app.models.NON_POLYMORPHIC_CASCADE, to='app.Scenario'),
        ),
    ]
