# Generated by Django 3.0 on 2020-12-01 18:52

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    # noinspection PyPep8Naming
    NodeResult = apps.get_model('app', 'NodeResult')
    NodeResult.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201201_1104'),
    ]

    operations = [
        migrations.RunPython(forward),
        migrations.RemoveField(
            model_name='noderesult',
            name='eval_job',
        ),
        migrations.AddField(
            model_name='noderesult',
            name='scenario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario'),
        ),
    ]
