# Generated by Django 3.0 on 2020-12-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201201_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noderesult',
            name='eval_job',
        ),
        migrations.AlterField(
            model_name='noderesult',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario'),
        ),
    ]
