# Generated by Django 3.0 on 2020-12-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201203_1048'),
        ('app', '0022_auto_20201201_1252'),
    ]

    operations = [
    ]
