# Generated by Django 3.0 on 2020-12-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_merge_20201204_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderesult',
            name='scenario_id',
            field=models.ForeignKey(db_column='scenario_id', on_delete=django.db.models.deletion.CASCADE, to='app.Scenario'),
        ),
    ]
