# Generated by Django 3.0 on 2020-12-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201204_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssolution',
            name='iterations',
            field=models.IntegerField(choices=[(100, 100), (1000, 1000), (5000, 5000), (10000, 10000), (25000, 25000), (50000, 50000)], null=True),
        ),
    ]
