# Generated by Django 3.0 on 2020-12-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_analyticssolution_layer_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssolution',
            name='layer_offset',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
