# Generated by Django 3.0 on 2020-12-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_analyticssolution_iterations'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='notes',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
