# Generated by Django 3.0 on 2020-12-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_analyticssolution_iterations'),
        ('app', '0020_auto_20201120_1619'),
    ]

    operations = [
    ]
