# Generated by Django 3.0 on 2020-12-15 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_merge_20201211_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdatasetinputchoice',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app.InputDataSetInput'),
        ),
    ]
