# Generated by Django 3.0 on 2020-12-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20201211_1307'),
        ('app', '0027_auto_20201215_1159'),
        ('app', '0027_auto_20201215_1715'),
    ]

    operations = [
    ]
