# Generated by Django 3.0 on 2020-12-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_merge_20201216_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
