# Generated by Django 3.0 on 2020-12-18 20:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201217_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodedata',
            name='input_data_set',
            field=models.ForeignKey(default=None, null=True, on_delete=app.models.NON_POLYMORPHIC_CASCADE, to='app.InputDataSet'),
        ),
    ]
