# Generated by Django 3.0 on 2020-12-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201217_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='last_modified',
            field=models.DateField(null=True),
        ),
    ]
