# Generated by Django 3.0 on 2020-12-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201217_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='status',
            field=models.CharField(blank=True, default='Unevaluated', max_length=256, null=True),
        ),
    ]
