# Generated by Django 3.0 on 2020-12-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201225_1359'),
        ('app', '0030_auto_20201229_1105'),
    ]

    operations = [
    ]
