# Generated by Django 3.0 on 2020-12-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_scenario_last_modified'),
        ('app', '0031_merge_20201230_1409'),
    ]

    operations = [
    ]
