# Generated by Django 3.0 on 2020-12-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_nodedata_input_data_set'),
        ('app', '0032_merge_20201230_1514'),
    ]

    operations = [
    ]
