# Generated by Django 3.0 on 2020-09-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20200914_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvalJob',
        ),
        migrations.DeleteModel(
            name='NodeData',
        ),
        migrations.DeleteModel(
            name='ScenarioNodeData',
        ),
    ]
