---
- name: Create a GCS bucket
  gcp_storage_bucket:
    name: dummy-engine-bucket
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: bucket

- name: Upload a file to GCS bucket
  gcp_storage_object:
    action: upload
    overwrite: yes
    bucket: "{{ bucket.name }}"
    src: "./dummy.json"
    dest: "{{ run_id }}.json"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
