---
- name: Destroy the instance
  gcp_compute_instance:
    name: "{{ instance_name }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

- name: Destroy the ip address
  gcp_compute_address:
    name: "{{ instance_name }}-ip"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
